"""Update of DB

Revision ID: fde0637b060d
Revises: b972baaa2cfd
Create Date: 2023-11-26 01:01:10.823587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde0637b060d'
down_revision: Union[str, None] = 'b972baaa2cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_id', table_name='category')
    op.drop_constraint('category_news_category_id_fkey', 'category_news', type_='foreignkey')
    op.drop_constraint('category_news_news_id_fkey', 'category_news', type_='foreignkey')
    op.create_foreign_key(None, 'category_news', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'category_news', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_comment_date', table_name='comment')
    op.drop_index('ix_comment_id', table_name='comment')
    op.drop_index('ix_news_date', table_name='news')
    op.drop_index('ix_news_id', table_name='news')
    op.drop_index('ix_site_id', table_name='site')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_site_id', 'site', ['id'], unique=False)
    op.create_index('ix_news_id', 'news', ['id'], unique=False)
    op.create_index('ix_news_date', 'news', ['date'], unique=False)
    op.create_index('ix_comment_id', 'comment', ['id'], unique=False)
    op.create_index('ix_comment_date', 'comment', ['date'], unique=False)
    op.drop_constraint(None, 'category_news', type_='foreignkey')
    op.drop_constraint(None, 'category_news', type_='foreignkey')
    op.create_foreign_key('category_news_news_id_fkey', 'category_news', 'news', ['news_id'], ['id'])
    op.create_foreign_key('category_news_category_id_fkey', 'category_news', 'category', ['category_id'], ['id'])
    op.create_index('ix_category_id', 'category', ['id'], unique=False)
    # ### end Alembic commands ###
