"""Update of Database

Revision ID: ecf4c0c37ac8
Revises: 6822250ed036
Create Date: 2023-11-24 21:48:59.369542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf4c0c37ac8'
down_revision: Union[str, None] = '6822250ed036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('site', sa.Integer(), nullable=True))
    op.drop_constraint('news_site_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'site', ['site'], ['id'])
    op.drop_column('news', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_site_id_fkey', 'news', 'site', ['site_id'], ['id'])
    op.drop_column('news', 'site')
    # ### end Alembic commands ###
