"""Update of relationships

Revision ID: b972baaa2cfd
Revises: 0e6e99904c4b
Create Date: 2023-11-25 10:30:03.589691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b972baaa2cfd'
down_revision: Union[str, None] = '0e6e99904c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_news', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('category_news', 'news_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_category_news_id', table_name='category_news')
    op.drop_column('category_news', 'id')
    op.drop_constraint('comment_news_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('news_site_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'site', ['site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_site_id_fkey', 'news', 'site', ['site_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_news_id_fkey', 'comment', 'news', ['news_id'], ['id'])
    op.add_column('category_news', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_category_news_id', 'category_news', ['id'], unique=False)
    op.alter_column('category_news', 'news_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category_news', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
