"""deleted column login from model User

Revision ID: 198150e2c209
Revises: ad8ded861204
Create Date: 2023-11-23 23:40:45.515166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198150e2c209'
down_revision: Union[str, None] = 'ad8ded861204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_login_key', 'user', type_='unique')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_login_key', 'user', ['login'])
    # ### end Alembic commands ###
