"""Update of Database

Revision ID: 8ee8d59b5550
Revises: 4a545201f9b8
Create Date: 2023-11-24 22:31:16.687560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ee8d59b5550'
down_revision: Union[str, None] = '4a545201f9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True,
               autoincrement=True)
    op.add_column('news', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_constraint('news_site_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'site', ['site_id'], ['id'])
    op.drop_column('news', 'site')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('site', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_site_fkey', 'news', 'site', ['site'], ['id'])
    op.drop_column('news', 'site_id')
    op.alter_column('comment', 'date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
