"""Update of Database

Revision ID: 09db25204bcb
Revises: 198150e2c209
Create Date: 2023-11-24 20:35:40.382847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09db25204bcb'
down_revision: Union[str, None] = '9ee09bdfa2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('comment', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               autoincrement=True)
    op.add_column('news', sa.Column('like', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('repost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'repost')
    op.drop_column('news', 'like')
    op.alter_column('comment', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               autoincrement=True)
    op.drop_column('category', 'is_active')
    # ### end Alembic commands ###
